name: riptv
description: An IPTV player application by ckgroup, specializing in M3U and Xtream Codes support.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  # UI & Material Design
  cupertino_icons: ^1.0.6
  lottie: ^3.0.0

  # Video Player
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
  better_player: ^0.0.83
  video_player: ^2.8.2
  chewie: ^1.7.5

  # Database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2

  # Networking
  http: ^1.1.0
  dio: ^5.4.0

  # State Management
  provider: ^6.1.1
  get: ^4.6.6

  # Screen & Window Management
  window_manager: ^0.3.7
  screen_retriever: ^0.1.9
  screen_brightness_windows: ^0.1.1

  # Utils
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  wakelock_plus: ^1.1.4
  package_info_plus: 8.0.2

  # Icons
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  isar_generator: ^3.1.0+1
  msix: ^3.16.6
  analyzer: ^5.13.0

flutter:
  uses-material-design: true
  assets:
    - config.json

msix_config:
  display_name: RIPTV
  publisher_display_name: ck
  identity_name: com.ck.iptvplayer
  msix_version: 1.0.0.0
  capabilities: 'internetClient,privateNetworkClientServer'
  languages: es-ES
